### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by Mervatabuamro** [HYF-Class21/workflows-group1-intro#5]
- [x] have a group repo [workflows-group1](https://github.com/HYF-Class21/workflows-group1-intro)
- [x] create one folder named groupone
- [x] create an img folder for members images
- [x] a nice README
- [x] have one well-named file per person
- [x] one pull requests for each group member
  - [x] linting checks pass
  - [x] code review checklist is complete
  - [x] the reviewer merged the code

**Comment by samirm00** [comment]
@Mervatabuamro, your link to the image in `READMe.md` is not correct it should be ![my image](./groupone/img/yourImageName.)

**Comment by Mervatabuamro** [comment]
@samirm00  I'm trying to make new updates to the Readme.md and add a new line with a different picture but its not working.

**Comment by samirm00** [comment]
@Mervatabuamro  well, do `git pull` on the master branch, create a new branch update the readme and make a new PR and it will work.
